import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#030712",
  },
  header: {
    backgroundColor: "#111827",
    paddingTop: 56,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#1f2937",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#e5e7eb",
    flex: 1,
  },
  content: {
    padding: 20,
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  dropdown: {
    flex: 1,
    backgroundColor: "#111827",
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownText: {
    color: "#e5e7eb",
    fontSize: 14,
  },
  searchRow: {
    flexDirection: "row",
    backgroundColor: "#111827",
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    color: "#e5e7eb",
    fontSize: 14,
  },
  sortRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  sortBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  sortBtnActive: {
    backgroundColor: "#22d3ee",
    borderColor: "#22d3ee",
  },
  sortBtnText: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "600",
  },
  sortBtnTextActive: {
    color: "#000",
  },
  dateGroup: {
    marginBottom: 16,
  },
  dateLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#9ca3af",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  eventRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  eventDate: {
    fontSize: 15,
    fontWeight: "500",
    color: "#e5e7eb",
  },
  eventMeta: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 2,
  },
  eventViewBtn: {
    color: "#22d3ee",
    fontSize: 14,
    fontWeight: "600",
  },
  empty: {
    color: "#6b7280",
    textAlign: "center",
    marginTop: 40,
    fontSize: 14,
  },
  error: {
    color: "#f87171",
    fontSize: 13,
    marginBottom: 12,
  },
  meta: {
    color: "#6b7280",
    fontSize: 12,
    marginBottom: 12,
  },
});