import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#030712",
    padding: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 48,
    marginBottom: 8,
  },
  logo: {
    fontSize: 22,
    fontWeight: "800",
    color: "#22d3ee",
    letterSpacing: 4,
  },
  logout: {
    color: "#6b7280",
    fontSize: 14,
  },
  welcome: {
    color: "#9ca3af",
    fontSize: 14,
    marginBottom: 16,
  },
  error: {
    color: "#f87171",
    fontSize: 13,
    marginBottom: 12,
  },
  alarmBanner: {
    backgroundColor: "#7f1d1d",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#f87171",
  },
  alarmBannerText: {
    color: "#fca5a5",
    fontWeight: "700",
    fontSize: 15,
    textAlign: "center",
  },
  cardRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  statLabel: {
    color: "#6b7280",
    fontSize: 12,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
  },
  modeBtn: {
    backgroundColor: "#1f2937",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#374151",
  },
  modeBtnText: {
    color: "#22d3ee",
    fontWeight: "600",
    fontSize: 15,
  },
  sectionTitle: {
    color: "#e5e7eb",
    fontWeight: "600",
    fontSize: 16,
    marginBottom: 12,
  },
  empty: {
    color: "#6b7280",
    fontSize: 14,
    marginBottom: 16,
  },
  eventCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#1f2937",
    gap: 12,
  },
  eventDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  eventType: {
    fontSize: 14,
    fontWeight: "500",
  },
  eventTime: {
    color: "#6b7280",
    fontSize: 12,
    marginTop: 2,
  },
  alarmTag: {
    backgroundColor: "#7f1d1d",
    color: "#fca5a5",
    fontSize: 11,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    overflow: "hidden",
  },
  actionRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 40,
  },
  actionBtn: {
    flex: 1,
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  actionBtnText: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "500",
  },
});